/* ***** BEGIN LICENSE BLOCK *****
 * 3e Calendar
 * Copyright © 2011  Zonio s.r.o.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * ***** END LICENSE BLOCK ***** */

#include "nsISupports.idl"

interface nsIMsgIdentity;

/**
 * Service running calendar synchronization on given accounts.
 */
[scriptable, uuid(3dc59b3e-5608-4415-9634-5cc9c91f2838)]
interface calEeeISynchronizationService: nsISupports {

  /**
   * Adds messaging and calendaring identity to list of accounts to
   * synchronize.
   *
   * @param identity messaging and calendaring identity to add
   * @return receiver
   */
  calEeeISynchronizationService addIdentity(in nsIMsgIdentity identity);

  /**
   * Removes messaging and calendaring identity from list of accounts
   * to synchronize.
   *
   * @param identityKey messaging and calendaring identity to remove
   * @return receiver
   */
  calEeeISynchronizationService removeIdentity(in ACString identityKey);

  /**
   * Registers itself in global context to observe changes in identities.
   *
   * @return receiver
   */
  calEeeISynchronizationService register();

  /**
   * Unregisters itself from global context.
   *
   * @return receiver
   */
  calEeeISynchronizationService unregister();

};

/**
 * Synchronizer of calendars present in Mozilla client application
 * (i.e. Lightning) with those on EEE server.
 */
[scriptable, uuid(17646dc9-178b-4a49-8201-d07167165331)]
interface calEeeISynchronizer: nsISupports {

    /**
     * EEE-enabled identity whose calendars are synchronized.
     */
    attribute nsIMsgIdentity identity;

    /**
     * Synchronizes identity's local EEE calendars with those on EEE
     * server.
     *
     * Calendars removed on server are deleted, new calendars on
     * server are added and properties of already loaded are taken
     * from values on server as well.
     *
     * @return receiver
     */
    calEeeISynchronizer synchronize();

};
